[package]
name = "egami"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "^1.15.0", features = ["derive"] }
smol = "^2.0.0"
winit = "0.30.0"
env_logger = "^0.11.3"
log = "^0.4.21"
wgpu = "0.20.0"
image = { version = "0.25.1", features = ["png"], default-features = false }